---
collections:
  - name: servicenow.itsm
    version: ">=1.0.0"
  - name: community.google
    version: ">=1.0.0"
  - name: ansible.posix
    version: ">=1.0.0"
  - name: ansible.utils
    version: ">=2.0.0"

roles:
  - name: geerlingguy.pip
    version: ">=2.0.0"
  - name: geerlingguy.python
    version: ">=2.0.0"
