---
- name: Inicializar checklist para incidente
  set_fact:
    checklist_actions: []
    next_steps: []
    incident_type: "{{ current_incident.category | default('unknown') }}"

- name: Determinar checklist baseado no tipo de incidente
  set_fact:
    checklist_items: "{{ incident_checklists[incident_type] | default([]) }}"

- name: Executar checklist de conectividade de rede
  include_tasks: "../../network_check/tasks/main.yml"
  when: 
    - incident_type == "network"
    - checklist_items | length > 0

- name: Executar checklist de hardware
  include_tasks: "../../hardware_check/tasks/main.yml"
  when: 
    - incident_type == "hardware"
    - checklist_items | length > 0

- name: Executar checklist de software
  include_tasks: "../../software_check/tasks/main.yml"
  when: 
    - incident_type == "software"
    - checklist_items | length > 0

- name: Executar checklist de segurança
  include_tasks: "../../security_check/tasks/main.yml"
  when: 
    - incident_type == "security"
    - checklist_items | length > 0

- name: Adicionar ação de verificação básica
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificação básica do sistema', 'status': 'Concluído'}] }}"

- name: Adicionar ação de análise de logs
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Análise de logs do sistema', 'status': 'Concluído'}] }}"

- name: Adicionar próximos passos padrão
  set_fact:
    next_steps: "{{ next_steps + ['Monitorar métricas do sistema', 'Verificar alertas relacionados', 'Documentar ações realizadas'] }}"

- name: Log do processamento do incidente
  debug:
    msg: |
      Processado incidente: {{ current_incident.number }}
      Tipo: {{ incident_type }}
      Ações realizadas: {{ checklist_actions | length }}
      Próximos passos: {{ next_steps | length }}
