---
- name: Checklist de Segurança - Verificar ameaças e vulnerabilidades
  debug:
    msg: "Executando checklist de segurança para incidente {{ current_incident.number }}"

- name: Verificar tentativas de login
  shell: "grep 'Failed password' /var/log/auth.log | tail -20"
  register: failed_logins
  changed_when: false
  ignore_errors: true

- name: Adicionar verificação de tentativas de login ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar tentativas de login', 'status': 'Concluído - ' + (failed_logins.stdout_lines | length | string) + ' tentativas falhadas'}] }}"

- name: Verificar usuários logados
  shell: "who"
  register: logged_users
  changed_when: false

- name: Adicionar verificação de usuários logados ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar usuários logados', 'status': 'Concluído - ' + (logged_users.stdout_lines | length | string) + ' usuários ativos'}] }}"

- name: Verificar processos suspeitos
  shell: "ps aux | grep -E '(nc|netcat|telnet|ssh|scp)' | grep -v grep"
  register: suspicious_processes
  changed_when: false

- name: Adicionar verificação de processos suspeitos ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar processos suspeitos', 'status': 'Concluído - ' + (suspicious_processes.stdout_lines | length | string) + ' processos encontrados'}] }}"

- name: Verificar conexões de rede ativas
  shell: "netstat -tuln | grep -E ':(22|23|80|443|8080)'"
  register: active_connections
  changed_when: false

- name: Adicionar verificação de conexões ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar conexões de rede ativas', 'status': 'Concluído - ' + (active_connections.stdout_lines | length | string) + ' conexões ativas'}] }}"

- name: Verificar integridade de arquivos críticos
  shell: "find /etc -name '*.conf' -exec md5sum {} \\; | head -10"
  register: file_integrity
  changed_when: false

- name: Adicionar verificação de integridade ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar integridade de arquivos críticos', 'status': 'Concluído - Checksums calculados'}] }}"

- name: Verificar configurações de firewall
  shell: "iptables -L -n"
  register: firewall_rules
  changed_when: false
  ignore_errors: true

- name: Adicionar verificação de firewall ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar configurações de firewall', 'status': 'Concluído - Regras de firewall verificadas' if firewall_rules.rc == 0 else 'Falha - Firewall não configurado'}] }}"

- name: Verificar logs de segurança
  shell: "journalctl --since '1 hour ago' | grep -i 'security\\|auth\\|fail' | tail -20"
  register: security_logs
  changed_when: false

- name: Adicionar verificação de logs de segurança ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar logs de segurança', 'status': 'Concluído - ' + (security_logs.stdout_lines | length | string) + ' eventos de segurança'}] }}"

- name: Verificar permissões de arquivos críticos
  shell: "ls -la /etc/passwd /etc/shadow /etc/sudoers"
  register: critical_permissions
  changed_when: false

- name: Adicionar verificação de permissões ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar permissões de arquivos críticos', 'status': 'Concluído - Permissões verificadas'}] }}"

- name: Verificar usuários com privilégios sudo
  shell: "grep -E '^[^:]*:.*:0:0:' /etc/passwd"
  register: sudo_users
  changed_when: false

- name: Adicionar verificação de usuários sudo ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar usuários com privilégios sudo', 'status': 'Concluído - ' + (sudo_users.stdout_lines | length | string) + ' usuários root encontrados'}] }}"

- name: Verificar processos rodando como root
  shell: "ps aux | grep '^root' | head -10"
  register: root_processes
  changed_when: false

- name: Adicionar verificação de processos root ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar processos rodando como root', 'status': 'Concluído - ' + (root_processes.stdout_lines | length | string) + ' processos root'}] }}"

- name: Verificar configurações de SSH
  shell: "grep -E '^(PermitRootLogin|PasswordAuthentication|Protocol)' /etc/ssh/sshd_config"
  register: ssh_config
  changed_when: false
  ignore_errors: true

- name: Adicionar verificação de SSH ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar configurações de SSH', 'status': 'Concluído - Configurações SSH verificadas' if ssh_config.rc == 0 else 'Falha - SSH não configurado'}] }}"

- name: Verificar atualizações de segurança pendentes
  shell: "apt list --upgradable 2>/dev/null | grep security || yum check-update --security 2>/dev/null || echo 'No security updates found'"
  register: security_updates
  changed_when: false

- name: Adicionar verificação de atualizações ao checklist
  set_fact:
    checklist_actions: "{{ checklist_actions + [{'name': 'Verificar atualizações de segurança pendentes', 'status': 'Concluído - Atualizações verificadas'}] }}"

- name: Adicionar próximos passos específicos de segurança
  set_fact:
    next_steps: "{{ next_steps + ['Analisar logs de segurança detalhados', 'Verificar configurações de IDS/IPS', 'Monitorar tentativas de acesso', 'Verificar backups de segurança'] }}"

- name: Log do checklist de segurança
  debug:
    msg: |
      Checklist de segurança concluído para incidente {{ current_incident.number }}
      Ações realizadas: {{ checklist_actions | length }}
      Próximos passos: {{ next_steps | length }}
