---
- name: Changes abertas (amostra de 10) + detalhes mínimos
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    host: "{{ snow_instance }}"
    username: "{{ snow_username }}"
    password: "{{ snow_password }}"

  tasks:
    # 1) Coleta única: changes abertas, ordenadas da mais recente p/ mais antiga
    - name: Buscar changes abertas (phase_state=open) ordenadas por abertura desc
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        sysparm_query: "active=true^phase_state=open^ORDERBYDESCopened_at"
        sysparm_display_value: "true"   # retorna valores legíveis (assigned_to, state etc.)
      register: abertas

    # 2) Cortar para apenas 10 itens
    - name: Amostra de 10
      set_fact:
        chg_all: "{{ abertas.records | default([]) }}"
        chg_top10: "{{ (abertas.records | default([]))[:10] }}"

    - name: Contagens
      debug:
        msg:
          - "Total retornado pela consulta: {{ chg_all | length }}"
          - "Mostrando apenas os 10 primeiros: {{ chg_top10 | length }}"

    # 3) Mostrar só os números (top 10)
    - name: Números das top 10 changes
      debug:
        msg: "{{ chg_top10 | map(attribute='number') | list }}"

    # 4) Mostrar um resumo útil por linha
    - name: Resumo (number | short_description | opened_at | last_update | assigned_to | state)
      debug:
        msg: >-
          {{ item.number }} | {{ item.short_description | default('') }}
          | opened_at={{ item.opened_at | default('') }}
          | last_update={{ item.sys_updated_on | default('') }}
          | owner={{ item.assigned_to | default('') }}
          | state={{ item.state | default('') }} / phase={{ item.phase_state | default('') }}
      loop: "{{ chg_top10 }}"
      loop_control:
        label: "{{ item.number }}"
