---
- name: Changes abertas + detalhes
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    snow_instance:
      host: "{{ snow_instance }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"

  tasks:
    - name: Buscar todas as changes abertas (phase_state=open)
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        sysparm_query: "active=true^phase_state=open"
        sysparm_display_value: "true"
      register: abertas

    - name: Guardar lista de números
      set_fact:
        change_numbers: "{{ abertas.records | map(attribute='number') | list }}"

    - name: Loop de detalhes por change
      debug:
        msg: |
          Change: {{ item.number }}
          Short Description: {{ item.short_description }}
          Description: {{ item.description }}
          Opened At: {{ item.opened_at }}
          Última Atualização: {{ item.sys_updated_on }}
      loop: "{{ abertas.records }}"
      loop_control:
        label: "{{ item.number }}"
