---
- name: Changes abertas (não-fechadas)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  tasks:
    - name: Buscar changes ativas e não-fechadas
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        sysparm_query: "active=true^phase_state=Open"
        sysparm_display_value: "true"
      register: result

    - debug:
        var: result.records