---
- name: Changes abertas + resumo (número, estado, horas sem update)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    snow_instance:
      host: "{{ snow_instance }}"
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"

  tasks:
    - name: Buscar todas as changes abertas (phase_state=open)
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        # usamos o valor "interno" (cru) que você mostrou: phase_state: open (minúsculo)
        sysparm_query: "active=true^phase_state=open"
        sysparm_display_value: "true"     # estado legível na saída
      register: abertas

    - name: Quantidade encontrada
      debug:
        msg: "Total de changes abertas encontradas: {{ abertas.records | length }}"

    - name: Epoch atual (segundos)
      set_fact:
        now_epoch: "{{ lookup('pipe','date -u +%s') | int }}"

    - name: Construir lista-resumo (number, state, horas_sem_update)
      set_fact:
        resumo_changes: >-
          {{ (resumo_changes | default([])) + [ {
              'number': item.number,
              'state': (item.state | string),
              'horas_sem_update': (
                (now_epoch -
                 (item.sys_updated_on
                   | to_datetime('%Y-%m-%d %H:%M:%S')
                   | to_timestamp)
                ) // 3600
              ) | int,
              'is_new': ((item.state | string) | lower == 'new')
            } ] }}
      loop: "{{ abertas.records | default([]) }}"
      when: (abertas.records | length) > 0
      loop_control:
        label: "{{ item.number }}"

    - name: Mensagem formatada (uma linha por change) - ou mensagem vazia
      debug:
        msg: >-
          {% if (resumo_changes | default([])) | length == 0 -%}
          Nenhuma change aberta encontrada com o filtro (active=true AND phase_state=open).
          {%- else -%}
          {% for r in resumo_changes %}
          - {{ "%-10s"|format(r.number) }} | state={{ "%-8s"|format(r.state) }} | {{ "%4dh"%(r.horas_sem_update) }} sem atualização{% if r.is_new %} | NEW{% endif %}
          {% endfor %}
          {%- endif %}
