- name: Criar incidentes de teste no ServiceNow com categorias diferentes
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    categorias_teste:
      - Software
      - Hardware
      - Network

  tasks:
    - name: Criar incidentes de teste
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
        state: present
        short_description: "Incidente de teste automático - Categoria {{ item }}"
        description: "Criado automaticamente para teste de SLA (Categoria: {{ item }})"
        impact: 3
        urgency: 2
        caller: "{{ sn_username }}"   # usar o mesmo usuário que você já autenticou
        other:
          category: "{{ item }}"
          work_notes: "Criado automaticamente via Ansible para testes"
      loop: "{{ categorias_teste }}"
      register: incidentes

    - name: Mostrar incidentes criados
      debug:
        msg: "Incidentes criados: {{ incidentes.results | map(attribute='record.number') | list }}"
