---
- name: Teste de notificação no Google Chat (webhook simples)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # google_chat_webhook_url: "https://chat.googleapis.com/v1/spaces/XXXX/messages?key=YYY&token=ZZZ"
    google_chat_webhook_url:
    mensagem_teste: "Teste de notificação: Ansible → Google Chat OK."

  tasks:
    - name: Enviar mensagem de texto para o Google Chat
      uri:
        url: "{{ google_chat_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body:
          text: "{{ mensagem_teste }}"
        status_code: 200
      register: chat_resp

    - name: Exibir resposta do Google Chat
      debug:
        var: chat_resp.json