---
- name: Classificação de incidentes + SLA customizado
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Regras de nomeação e resolução (em minutos)
    nomeacao_minutos:
      1: 15      # P1 - CRITICAL
      2: 30      # P2 - HIGH
      3: 90      # P3 - MEDIUM
      4: 180     # P4 - LOW
    resolucao_minutos:
      1: 240     # P1 - 4h
      2: 900     # P2 - 15h
      3: 3600    # P3 - 2,5 dias
      4: 7200    # P4 - 5 dias

  vars_files:
    - "vars_incident.yml"   # deve conter: records: [...]

  pre_tasks:
    - name: Validar 'records' do vars_incident.yml
      assert:
        that:
          - records is defined
          - records | type_debug == 'list'
        fail_msg: "Esperava 'records' como lista em vars_incident.yml."

  tasks:
    - name: Epoch atual (UTC)
      set_fact:
        now_epoch: "{{ lookup('pipe','date -u +%s') | int }}"

    - name: Normalizar lista de incidentes
      set_fact:
        inc_all: "{{ records | default([]) }}"

    - name: Inicializar buckets
      set_fact:
        fora_nomeacao: []   # sem responsável dentro do prazo de nomeação
        fora_resolucao: []  # ainda abertos mas já violaram prazo de resolução
        near_breach: []     # próximos de violar prazo de resolução

    # --------- 1) Fora do prazo de nomeação ---------
    - name: Classificar incidentes fora do prazo de nomeação
      set_fact:
        fora_nomeacao: "{{ fora_nomeacao + [ item ] }}"
      vars:
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('')) | quote ) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0
          }}
        delta_open_sec: "{{ (now_epoch | int) - (opened_epoch | int) }}"
        tem_owner: >-
          {{ (item.assigned_to is defined) and ((item.assigned_to | string | trim) != '') }}
      loop: "{{ inc_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - (opened_epoch | int) > 0
        - not tem_owner
        - (delta_open_sec | int) >= (nomeacao_minutos[item.priority | int] * 60)

    # --------- 2) Fora do prazo de resolução ---------
    - name: Classificar incidentes fora do prazo de resolução
      set_fact:
        fora_resolucao: "{{ fora_resolucao + [ item ] }}"
      vars:
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('')) | quote ) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0
          }}
        delta_open_sec: "{{ (now_epoch | int) - (opened_epoch | int) }}"
      loop: "{{ inc_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - (opened_epoch | int) > 0
        - (delta_open_sec | int) >= (resolucao_minutos[item.priority | int] * 60)

    # --------- 3) Próximos de violar SLA (<= 60 min) ---------
    - name: Classificar incidentes próximos de violar SLA
      set_fact:
        near_breach: "{{ near_breach + [ item ] }}"
      vars:
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('')) | quote ) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0
          }}
        deadline_epoch: "{{ (opened_epoch | int) + (resolucao_minutos[item.priority | int] * 60) }}"
        time_left_sec: "{{ (deadline_epoch | int) - (now_epoch | int) }}"
      loop: "{{ inc_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - (opened_epoch | int) > 0
        - (time_left_sec | int) > 0
        - (time_left_sec | int) <= (60 * 60)

    # ------------------ Saídas / Resumo ------------------
    - name: Contagens por bucket
      debug:
        msg:
          - "Fora do prazo de nomeação: {{ fora_nomeacao | length }}"
          - "Fora do prazo de resolução: {{ fora_resolucao | length }}"
          - "Próximos de violar SLA (≤60min): {{ near_breach | length }}"

    - name: Listas simples por bucket
      debug:
        msg:
          fora_nomeacao: "{{ fora_nomeacao | map(attribute='number') | list }}"
          fora_resolucao: "{{ fora_resolucao | map(attribute='number') | list }}"
          near_breach: "{{ near_breach | map(attribute='number') | list }}"

    # --------- 4) Notificação Google Chat ---------
    - name: Montar mensagem final
      set_fact:
        chat_text: |-
          *Resumo SLA Incidentes*
          - Fora do prazo de nomeação: {{ fora_nomeacao | length }}
          - Fora do prazo de resolução: {{ fora_resolucao | length }}
          - Próximos de violar SLA (≤60min): {{ near_breach | length }}

          *Tickets fora nomeação:* {{ fora_nomeacao | map(attribute='number') | list }}
          *Tickets fora resolução:* {{ fora_resolucao | map(attribute='number') | list }}
          *Tickets próximos SLA:* {{ near_breach | map(attribute='number') | list }}

    - name: Pré-visualizar mensagem
      debug:
        var: chat_text

    - name: Enviar mensagem para Google Chat
      uri:
        url: "{{ google_chat_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body:
          text: "{{ chat_text }}"
        status_code: 200
      when: google_chat_webhook_url is defined
