---
- name: Buckets (Novas sem owner, SLA perto, Violadas + 24h sem update) a partir de variáveis locais
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm    # NÃO inclua community.general aqui

  vars:
    window_minutes_new: 15     # "novas" = abertas nos últimos X minutos
    near_breach_minutes: 60    # SLA expira em <= X minutos
    stale_hours: 24            # Sem atualização há >= X horas (para violadas)

  vars_files:
    - "vars.yml"   # contém: records: [...]
    - "slas.yml"   # contém: slas: [...]

  pre_tasks:
    - name: Validar 'records' (changes)
      assert:
        that:
          - records is defined
          - records | type_debug == 'list'
        fail_msg: "Esperava 'records' como lista em vars.yml."

    - name: Garantir que 'slas' exista (pode ser lista vazia)
      set_fact:
        slas: "{{ slas | default([]) }}"

  tasks:
    # ========= Base temporal =========
    - name: Agora (UTC epoch)
      set_fact:
        now_epoch: "{{ lookup('pipe','date -u +%s') | int }}"

    # ========= Normalizações =========
    - name: Normalizar CHGs
      set_fact:
        chg_all: "{{ records }}"

    # >>>> Sem json_query: construir mapas com zip <<<<
    - name: Mapa sys_id -> number
      set_fact:
        map_sysid_to_number: >-
          {{
            dict(
              (chg_all | map(attribute='sys_id')   | list)
              | zip(chg_all | map(attribute='number') | list)
            )
          }}

    - name: Mapa number -> sys_id
      set_fact:
        map_number_to_sysid: >-
          {{
            dict(
              (chg_all | map(attribute='number') | list)
              | zip(chg_all | map(attribute='sys_id')   | list)
            )
          }}

    # ========= Buckets =========
    - name: Inicializar buckets
      set_fact:
        novos_sem_owner: []
        near_breach: []
        violadas_stale: []

    # -------- 1) Novos e sem tratamento --------
    - name: Classificar "Novos e sem tratamento"
      set_fact:
        novos_sem_owner: "{{ novos_sem_owner + [ novo_reg ] }}"
      vars:
        opened_epoch: >-
          {{ (lookup('pipe', 'date -u -d ' ~ (item.opened_at | quote) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0 }}
        delta_open_sec: "{{ (now_epoch | int) - (opened_epoch | int) }}"
        minutos_aberto: "{{ (delta_open_sec // 60) | int }}"
        sem_owner: >-
          {{ (item.assigned_to is not defined) or ((item.assigned_to | string | trim) == '') }}
        novo_reg: >-
          {{
            {
              'number': item.number,
              'sys_id': item.sys_id,
              'short_description': item.short_description | default(''),
              'opened_at': item.opened_at | default(''),
              'minutes_open': minutos_aberto | int
            }
          }}
      loop: "{{ chg_all }}"
      loop_control: { label: "{{ item.number | default('sem-number') }}" }
      when:
        - item.opened_at is defined
        - (item.opened_at | string | length) > 0
        - sem_owner
        - delta_open_sec | int <= (window_minutes_new | int) * 60

    # -------- Preparar SLAs normalizados --------
    - name: Normalizar SLAs (planned_end_epoch, has_breached bool, chg_number)
      set_fact:
        slas_norm: >-
          {%- set out = [] -%}
          {%- for s in slas -%}
          {%- set breached = ( s.has_breached if (s.has_breached is boolean)
                               else ((s.has_breached | default('false') | string | lower) == 'true') ) -%}
          {%- set pend = (lookup('pipe', 'date -u -d ' ~ ( (s.planned_end_time | default('') ) | quote ) ~ ' +%s') | int)
                          if (s.planned_end_time is defined and (s.planned_end_time | string | length) > 0) else 0 -%}
          {%- set num = ( s.task_number | default('') ) -%}
          {%- if not num and (s.task is defined) and (s.task in map_sysid_to_number) -%}
            {%- set num = map_sysid_to_number[s.task] -%}
          {%- endif -%}
          {%- set rec = {
                'task_sys_id': (s.task | default('')),
                'task_number': num,
                'planned_end_epoch': pend,
                'planned_end_time': (s.planned_end_time | default('')),
                'has_breached': breached,
                'stage': (s.stage | default(''))
              } -%}
          {%- do out.append(rec) -%}
          {%- endfor -%}
          {{ out }}

    # -------- 2) SLA próximo de violar --------
    - name: Classificar "SLA próximo de violar"
      set_fact:
        near_breach: "{{ (near_breach + [ nb_reg ]) | unique }}"
      vars:
        chg_num: "{{ item.task_number | default('') }}"
        time_left_sec: "{{ (item.planned_end_epoch | int) - (now_epoch | int) }}"
        nb_reg: >-
          {{
            {
              'number': chg_num,
              'minutes_left': (time_left_sec // 60) | int,
              'planned_end_time': item.planned_end_time
            }
          }}
      loop: "{{ slas_norm }}"
      loop_control: { label: "{{ item.task_number | default(item.task_sys_id | default('sem-task')) }}" }
      when:
        - item.has_breached == false
        - item.planned_end_epoch | int > 0
        - time_left_sec | int >= 0
        - time_left_sec | int <= (near_breach_minutes | int) * 60
        - chg_num | length > 0

    # -------- 3) Violadas e ≥24h sem atualização --------
    - name: Classificar "Violadas e sem atualização há >= {{ stale_hours }}h"
      set_fact:
        violadas_stale: "{{ (violadas_stale + [ vs_reg ]) | unique }}"
      vars:
        chg_num: "{{ item.task_number | default('') }}"
        chg_sysid: >-
          {{
            (item.task_sys_id)
              if (item.task_sys_id is defined and (item.task_sys_id | string | length) > 0)
              else ( map_number_to_sysid[chg_num] if (chg_num in map_number_to_sysid) else '' )
          }}
        chg_obj: "{{ (chg_all | selectattr('sys_id','equalto', chg_sysid) | list | first) | default({}) }}"
        updated_epoch: >-
          {{ (lookup('pipe','date -u -d ' ~ ( (chg_obj.sys_updated_on | default('') ) | quote ) ~ ' +%s') | int)
              if (chg_obj.sys_updated_on is defined and (chg_obj.sys_updated_on | string | length) > 0) else 0 }}
        opened_epoch: >-
          {{ (lookup('pipe','date -u -d ' ~ ( (chg_obj.opened_at | default('') ) | quote ) ~ ' +%s') | int)
              if (chg_obj.opened_at is defined and (chg_obj.opened_at | string | length) > 0) else 0 }}
        hours_since_update: "{{ ((now_epoch | int) - (updated_epoch | int)) // 3600 }}"
        hours_open: "{{ ((now_epoch | int) - (opened_epoch | int)) // 3600 }}"
        vs_reg: >-
          {{
            {
              'number': chg_num,
              'last_update': chg_obj.sys_updated_on | default(''),
              'hours_since_update': hours_since_update | int,
              'opened_at': chg_obj.opened_at | default(''),
              'hours_open': hours_open | int
            }
          }}
      loop: "{{ slas_norm }}"
      loop_control: { label: "{{ item.task_number | default(item.task_sys_id | default('sem-task')) }}" }
      when:
        - item.has_breached == true
        - chg_num | length > 0
        - updated_epoch | int > 0
        - ((now_epoch | int) - (updated_epoch | int)) >= (stale_hours | int) * 3600

    # ========= Saídas =========
    - name: Contagens por bucket
      debug:
        msg:
          - "Novos e sem owner (<= {{ window_minutes_new }} min): {{ novos_sem_owner | length }}"
          - "SLA próximo (<= {{ near_breach_minutes }} min): {{ near_breach | length }}"
          - "Violadas + sem update >= {{ stale_hours }}h: {{ violadas_stale | length }}"

    - name: Listas de números por bucket
      debug:
        msg:
          novos_sem_owner: "{{ novos_sem_owner | map(attribute='number') | list }}"
          near_breach:     "{{ near_breach     | map(attribute='number') | list }}"
          violadas_stale:  "{{ violadas_stale  | map(attribute='number') | list }}"

    - name: Detalhes | Novos e sem owner
      debug:
        var: novos_sem_owner

    - name: Detalhes | SLA próximo de violar
      debug:
        var: near_breach

    - name: Detalhes | Violadas e >= {{ stale_hours }}h sem update
      debug:
        var: violadas_stale

    - name: Mensagem pronta (resumo texto p/ Google Chat)
      set_fact:
        chat_text: |-
          *Novos e sem owner (<= {{ window_minutes_new }} min):* {{ novos_sem_owner | map(attribute='number') | list }}
          *SLA próximo (<= {{ near_breach_minutes }} min):* {{ near_breach | map(attribute='number') | list }}
          *Violadas + sem update >= {{ stale_hours }}h:* {{ violadas_stale | map(attribute='number') | list }}

    - name: Pré-visualizar mensagem
      debug:
        var: chat_text
