---
- name: Classificar tickets por buckets
  hosts: localhost
  gather_facts: no
  vars:
    offline_mode: true  # false = busca task_sla
    now: "{{ lookup('pipe', 'date +%s') | int }}"
    fifteen_minutes: 900
    twenty_four_hours: 86400

  tasks:
    - name: Carregar tickets
      set_fact:
        tickets: "{{ lookup('file', 'tickets.json') | from_json }}"

    - name: Classificar tickets
      set_fact:
        bucket_novos_sem_owner: "{{ bucket_novos_sem_owner | default([]) }}"
        bucket_sla_proximo: "{{ bucket_sla_proximo | default([]) }}"
        bucket_violados_sem_update: "{{ bucket_violados_sem_update | default([]) }}"
        bucket_sem_update: "{{ bucket_sem_update | default([]) }}"

    - name: Processar tickets
      set_fact:
        bucket_novos_sem_owner: >-
          {{ bucket_novos_sem_owner + [item] if (
            (now - (item.opened_at | to_datetime('%Y-%m-%d %H:%M:%S') | to_datetime | to_timestamp)) <= fifteen_minutes
            and (item.assigned_to | length == 0)
          ) or (
            (now - (item.opened_at | to_datetime('%Y-%m-%d %H:%M:%S') | to_datetime | to_timestamp)) >= twenty_four_hours
            and (item.assigned_to | length == 0)
          )
          else bucket_novos_sem_owner }}
        bucket_sla_proximo: >-
          {{ bucket_sla_proximo + [item] if (
            not offline_mode
              and item.sla_time_remaining is defined and item.sla_time_remaining <= fifteen_minutes
          ) or (
            offline_mode
              and (item.sla_due | length > 0)
              and ((item.sla_due | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp) - now) <= fifteen_minutes
              and ((item.sla_due | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp) - now) > 0
          )
          else bucket_sla_proximo }}
        bucket_violados_sem_update: >-
          {{ bucket_violados_sem_update + [item] if (
            not offline_mode
              and item.sla_status == 'Breached'
              and (now - (item.sys_updated_on | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp)) >= twenty_four_hours
          ) or (
            offline_mode
              and (item.sla_due | length > 0)
              and (item.sla_due | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp) < now
              and (now - (item.sys_updated_on | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp)) >= twenty_four_hours
          )
          else bucket_violados_sem_update }}
        bucket_sem_update: >-
          {{ bucket_sem_update + [item] if (
            now - (item.sys_updated_on | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp) >= twenty_four_hours
          ) else bucket_sem_update }}
      loop: "{{ tickets }}"

    - name: Exibir resultados
      debug:
        msg:
          - "Novos e sem owner: {{ bucket_novos_sem_owner | length }}"
          - "SLA próximo de violar: {{ bucket_sla_proximo | length }}"
          - "Violados + sem atualização ≥ 24h: {{ bucket_violados_sem_update | length }}"
          - "Sem atualização (parados): {{ bucket_sem_update | length }}"
