---
- name: Buckets offline + SLA (near breach / violadas) a partir de records do vars.yml
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Limiares ajustáveis
    window_minutes_new: 15    # "novos" = abertos nos últimos X minutos
    ownerless_hours: 24       # "velhos sem owner" = abertos há >= X horas sem owner
    stale_hours: 24           # "sem atualização" = sem update há >= X horas
    near_breach_minutes: 60   # "SLA próximo" = prazo em <= X minutos

  # Entrada offline (sem chamadas ao ServiceNow aqui)
  vars_files:
    - "vars.yml"    # deve conter: records: [...]

  pre_tasks:
    - name: Validar 'records' do vars.yml
      assert:
        that:
          - records is defined
          - records | type_debug == 'list'
        fail_msg: "Esperava 'records' como lista em vars.yml."

  tasks:
    - name: Epoch atual (UTC)
      set_fact:
        now_epoch: "{{ lookup('pipe','date -u +%s') | int }}"

    - name: Normalizar lista de changes
      set_fact:
        chg_all: "{{ records | default([]) }}"

    - name: Inicializar buckets
      set_fact:
        # buckets sem depender de SLA
        novos_sem_owner: []
        velhos_sem_owner: []
        sem_atualizacao_sem_owner: []
        sem_atualizacao_com_owner: []
        # buckets de SLA (ficam vazios se não houver sla_due/due_date)
        near_breach: []
        violadas_stale: []

    # --------- 1) Novos e sem owner (≤ window_minutes_new) ---------
    - name: Classificar "Novos e sem owner"
      set_fact:
        novos_sem_owner: "{{ novos_sem_owner + [ novo_reg ] }}"
      vars:
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('') ) | quote ) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0
          }}
        delta_open_sec: "{{ (now_epoch | int) - (opened_epoch | int) }}"
        sem_owner: >-
          {{ (item.assigned_to is not defined) or ((item.assigned_to | string | trim) == '') }}
        novo_reg: >-
          {{
            {
              'number': item.number,
              'sys_id': item.sys_id,
              'short_description': item.short_description | default(''),
              'opened_at': item.opened_at | default(''),
              'minutes_open': ((delta_open_sec | int) // 60) | int
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - opened_epoch | int > 0
        - sem_owner
        - (delta_open_sec | int) <= (window_minutes_new | int) * 60

    # --------- 1b) Velhos sem owner (≥ ownerless_hours) -----------
    - name: Classificar "Velhos sem owner" (abertos há >= ownerless_hours)
      set_fact:
        velhos_sem_owner: "{{ velhos_sem_owner + [ velho_reg ] }}"
      vars:
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('') ) | quote ) ~ ' +%s') | int)
              if (item.opened_at is defined and (item.opened_at | string | length) > 0) else 0
          }}
        delta_open_sec: "{{ (now_epoch | int) - (opened_epoch | int) }}"
        sem_owner: >-
          {{ (item.assigned_to is not defined) or ((item.assigned_to | string | trim) == '') }}
        velho_reg: >-
          {{
            {
              'number': item.number,
              'sys_id': item.sys_id,
              'short_description': item.short_description | default(''),
              'opened_at': item.opened_at | default(''),
              'hours_open': ((delta_open_sec | int) // 3600) | int
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - opened_epoch | int > 0
        - sem_owner
        - (delta_open_sec | int) >= (ownerless_hours | int) * 3600

    # --------- 2) Sem atualização ≥ stale_hours (sem owner) --------
    - name: Classificar "Sem atualização (sem owner) >= stale_hours"
      set_fact:
        sem_atualizacao_sem_owner: "{{ sem_atualizacao_sem_owner + [ stale_reg ] }}"
      vars:
        updated_epoch: >-
          {{
            (lookup('pipe','date -u -d ' ~ ( (item.sys_updated_on | default('') ) | quote ) ~ ' +%s') | int)
              if (item.sys_updated_on is defined and (item.sys_updated_on | string | length) > 0) else 0
          }}
        delta_update_sec: "{{ (now_epoch | int) - (updated_epoch | int) }}"
        sem_owner: >-
          {{ (item.assigned_to is not defined) or ((item.assigned_to | string | trim) == '') }}
        stale_reg: >-
          {{
            {
              'number': item.number,
              'sys_id': item.sys_id,
              'short_description': item.short_description | default(''),
              'last_update': item.sys_updated_on | default(''),
              'hours_since_update': ((delta_update_sec | int) // 3600) | int
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - updated_epoch | int > 0
        - sem_owner
        - (delta_update_sec | int) >= (stale_hours | int) * 3600

    # --------- 3) Sem atualização ≥ stale_hours (com owner) --------
    - name: Classificar "Sem atualização (com owner) >= stale_hours"
      set_fact:
        sem_atualizacao_com_owner: "{{ sem_atualizacao_com_owner + [ stale_reg ] }}"
      vars:
        updated_epoch: >-
          {{
            (lookup('pipe','date -u -d ' ~ ( (item.sys_updated_on | default('') ) | quote ) ~ ' +%s') | int)
              if (item.sys_updated_on is defined and (item.sys_updated_on | string | length) > 0) else 0
          }}
        delta_update_sec: "{{ (now_epoch | int) - (updated_epoch | int) }}"
        tem_owner: >-
          {{ (item.assigned_to is defined) and ((item.assigned_to | string | trim) != '') }}
        stale_reg: >-
          {{
            {
              'number': item.number,
              'sys_id': item.sys_id,
              'assigned_to': item.assigned_to | default(''),
              'short_description': item.short_description | default(''),
              'last_update': item.sys_updated_on | default(''),
              'hours_since_update': ((delta_update_sec | int) // 3600) | int
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - updated_epoch | int > 0
        - tem_owner
        - (delta_update_sec | int) >= (stale_hours | int) * 3600

    # ======================= SLA (OFFLINE) =========================
    # 4) SLA próximo de violar — usando SLA local da change (sla_due ou due_date)
    - name: (OFFLINE) Classificar "SLA próximo de violar" usando sla_due/due_date
      set_fact:
        near_breach: "{{ near_breach + [ nb_reg ] }}"
      vars:
        # preferir sla_due; se vazio, tentar due_date
        deadline_str: >-
          {{
            (item.sla_due | default('')) if (item.sla_due is defined and (item.sla_due | string | length) > 0)
            else (item.due_date | default(''))
          }}
        due_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ (deadline_str | quote) ~ ' +%s') | int)
              if (deadline_str | string | length) > 0 else 0
          }}
        time_left_sec: "{{ (due_epoch | int) - (now_epoch | int) }}"
        nb_reg: >-
          {{
            {
              'number': item.number,
              'minutes_left': ((time_left_sec | int) // 60) | int,
              'deadline': deadline_str
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - due_epoch | int > 0
        - time_left_sec | int >= 0
        - time_left_sec | int <= (near_breach_minutes | int) * 60

    # 5) Violadas + sem atualização ≥ stale_hours — inferidas por prazo ultrapassado
    - name: (OFFLINE) Classificar "Violadas e sem atualização há >= stale_hours" por deadline ultrapassado
      set_fact:
        violadas_stale: "{{ violadas_stale + [ vs_reg ] }}"
      vars:
        # preferir sla_due; se vazio, tentar due_date
        deadline_str: >-
          {{
            (item.sla_due | default('')) if (item.sla_due is defined and (item.sla_due | string | length) > 0)
            else (item.due_date | default(''))
          }}
        due_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ (deadline_str | quote) ~ ' +%s') | int)
              if (deadline_str | string | length) > 0 else 0
          }}
        updated_epoch: >-
          {{
            (lookup('pipe','date -u -d ' ~ ( (item.sys_updated_on | default('') ) | quote ) ~ ' +%s') | int)
              if (item.sys_updated_on is defined and (item.sys_updated_on | string | length) > 0) else 0
          }}
        time_left_sec: "{{ (due_epoch | int) - (now_epoch | int) }}"
        hours_since_update: "{{ ((now_epoch | int) - (updated_epoch | int)) // 3600 }}"
        vs_reg: >-
          {{
            {
              'number': item.number,
              'deadline': deadline_str,
              'last_update': item.sys_updated_on | default(''),
              'hours_since_update': (hours_since_update | int)
            }
          }}
      loop: "{{ chg_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when:
        - due_epoch | int > 0
        - time_left_sec | int < 0
        - updated_epoch | int > 0
        - hours_since_update | int >= (stale_hours | int)

    # ------------------ Saídas / Resumo ------------------
    - name: Contagens por bucket (inclui SLA)
      debug:
        msg:
          - "Novos e sem owner (≤ {{ window_minutes_new }} min): {{ novos_sem_owner | length }}"
          - "Velhos sem owner (≥ {{ ownerless_hours }} h): {{ velhos_sem_owner | length }}"
          - "Sem atualização (SEM owner) ≥ {{ stale_hours }} h: {{ sem_atualizacao_sem_owner | length }}"
          - "Sem atualização (COM owner) ≥ {{ stale_hours }} h: {{ sem_atualizacao_com_owner | length }}"
          - "SLA próximo (≤ {{ near_breach_minutes }} min): {{ near_breach | length }}"
          - "Violadas + sem update ≥ {{ stale_hours }} h: {{ violadas_stale | length }}"

    - name: Listas de números por bucket (inclui SLA)
      debug:
        msg:
          novos_sem_owner:            "{{ novos_sem_owner             | map(attribute='number') | list }}"
          velhos_sem_owner:           "{{ velhos_sem_owner            | map(attribute='number') | list }}"
          sem_atualizacao_sem_owner:  "{{ sem_atualizacao_sem_owner   | map(attribute='number') | list }}"
          sem_atualizacao_com_owner:  "{{ sem_atualizacao_com_owner   | map(attribute='number') | list }}"
          near_breach:                "{{ near_breach                 | map(attribute='number') | list }}"
          violadas_stale:             "{{ violadas_stale              | map(attribute='number') | list }}"

    - name: Mensagem pronta (resumo para Chat)
      set_fact:
        chat_text: |-
          *Novos e sem owner (≤ {{ window_minutes_new }} min):* {{ novos_sem_owner | map(attribute='number') | list }}
          *Velhos sem owner (≥ {{ ownerless_hours }} h):* {{ velhos_sem_owner | map(attribute='number') | list }}
          *Sem atualização (SEM owner) ≥ {{ stale_hours }} h:* {{ sem_atualizacao_sem_owner | map(attribute='number') | list }}
          *Sem atualização (COM owner) ≥ {{ stale_hours }} h:* {{ sem_atualizacao_com_owner | map(attribute='number') | list }}
          *SLA próximo (≤ {{ near_breach_minutes }} min):* {{ near_breach | map(attribute='number') | list }}
          *Violadas + sem update ≥ {{ stale_hours }} h:* {{ violadas_stale | map(attribute='number') | list }}

    - name: Pré-visualizar mensagem
      debug:
        var: chat_text
