---
- name: Buckets de incidentes baseados em prioridade e SLAs customizados
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Regras SLA por prioridade (minutos para nome, horas para resolver)
    sla_rules:
      1: { name_time_min: 15,   resolve_time_h: 4   }   # P1 CRITICAL
      2: { name_time_min: 30,   resolve_time_h: 15  }   # P2 HIGH
      3: { name_time_min: 90,   resolve_time_h: 60  }   # P3 MEDIUM (2,5 dias ≈ 60h)
      4: { name_time_min: 180,  resolve_time_h: 120 }   # P4 LOW (5 dias ≈ 120h)

  vars_files:
    - "vars_incident.yml"   # deve conter: records: [...]

  tasks:
    - name: Epoch atual (UTC)
      set_fact:
        now_epoch: "{{ lookup('pipe','date -u +%s') | int }}"

    - name: Normalizar lista de incidentes
      set_fact:
        inc_all: "{{ records | default([]) }}"

    - name: Inicializar buckets
      set_fact:
        fora_nomeacao: []      # passaram do prazo de nomeação (owner vazio)
        fora_resolucao: []     # passaram do prazo de resolução (mesmo resolvidos não?)
        dentro_sla: []         # ainda dentro do prazo

    - name: Classificar incidentes por prioridade e SLA
      set_fact:
        fora_nomeacao: "{{ fora_nomeacao + ([ reg ] if sla_breach_nome else []) }}"
        fora_resolucao: "{{ fora_resolucao + ([ reg ] if sla_breach_resolve else []) }}"
        dentro_sla: "{{ dentro_sla + ([ reg ] if (not sla_breach_nome and not sla_breach_resolve) else []) }}"
      vars:
        # Epochs
        opened_epoch: >-
          {{
            (lookup('pipe', 'date -u -d ' ~ ( (item.opened_at | default('') ) | quote ) ~ ' +%s') | int)
              if (item.opened_at | default('') | length > 0) else 0
          }}
        delta_min: "{{ ((now_epoch - opened_epoch) // 60) | int }}"
        delta_h:   "{{ ((now_epoch - opened_epoch) // 3600) | int }}"

        # SLA thresholds pela prioridade
        pri: "{{ (item.priority | default('4')) | int }}"
        name_time_min: "{{ sla_rules[pri].name_time_min | int }}"
        resolve_time_h: "{{ sla_rules[pri].resolve_time_h | int }}"

        # Condições de breach
        sem_owner: "{{ (item.assigned_to | default('') | trim) == '' }}"
        sla_breach_nome: "{{ sem_owner and (delta_min > name_time_min) }}"
        sla_breach_resolve: "{{ delta_h > resolve_time_h }}"

        # Registro resumido
        reg:
          number: "{{ item.number }}"
          sys_id: "{{ item.sys_id }}"
          priority: "{{ item.priority }}"
          short_description: "{{ item.short_description | default('') }}"
          opened_at: "{{ item.opened_at }}"
          minutes_open: "{{ delta_min }}"
          hours_open: "{{ delta_h }}"
          assigned_to: "{{ item.assigned_to | default('None') }}"
      loop: "{{ inc_all }}"
      loop_control:
        label: "{{ item.number | default('sem-number') }}"
      when: opened_epoch > 0

    # ------------------ Saídas ------------------
    - name: Contagens por bucket
      debug:
        msg:
          - "Fora do prazo de nomeação: {{ fora_nomeacao | length }}"
          - "Fora do prazo de resolução: {{ fora_resolucao | length }}"
          - "Dentro do SLA: {{ dentro_sla | length }}"

    - name: Listas simples (números)
      debug:
        msg:
          fora_nomeacao: "{{ fora_nomeacao | map(attribute='number') | list }}"
          fora_resolucao: "{{ fora_resolucao | map(attribute='number') | list }}"
          dentro_sla: "{{ dentro_sla | map(attribute='number') | list }}"
